{"name": "Ошибка при неверном пароле", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующим паролем", "steps": [{"name": "Отправка запроса на авторизацию с несуществующим паролем", "status": "passed", "steps": [{"name": "Авторизация пользователя", "status": "passed", "parameters": [{"name": "email", "value": "'user_1bda08ed@test.com'"}, {"name": "password", "value": "'nonepassword'"}], "start": 1757335233615, "stop": 1757335234019}], "start": 1757335233615, "stop": 1757335234019}, {"name": "Проверяем, что при создании пользователя без обязательного поля код ответ 401 и success: false", "status": "passed", "start": 1757335234019, "stop": 1757335234019}, {"name": "Проверяем что сообщение об ошибке: email or password are incorrect", "status": "passed", "start": 1757335234019, "stop": 1757335234019}], "start": 1757335233614, "stop": 1757335234021, "uuid": "dde6d81f-d46f-4519-9fd3-a1307a684a65", "historyId": "4b57dcbac64f372a558af3f3c4dbc79a", "testCaseId": "4b57dcbac64f372a558af3f3c4dbc79a", "fullName": "tests.test_auth_user.TestAuthUser#test_auth_user_invalid_password_failed", "labels": [{"name": "feature", "value": "API: Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_user"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "25768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_user"}]}